#
# This config file is loadded **ONLY** in local development.
# It will be replaced by a config/config.json request when served with wire app serve.
#

app:
  name: Arena
storage:
  persistent: true
  path: dxos/arena-local
wns:
  server: "https://wns1.kube.moon.dxos.network/api"
  chainId: "devnet-2"
sentry:
  dsn: http://c4520c11e2c14d799a2802f59495ac49@sentry.kube.dxos.network/2
  environment: development
