#
# This config file is loadded **ONLY** in local development.
# It will be replaced by a config/config.json request when served with dx app serve.
#

app:
  name: Arena
storage:
  persistent: true
  path: dxos/arena-local
registry:
  server: "https://apollo1.kube.moon.dxos.network/dxos/wns/api"
  chainId: "devnet-2"
sentry:
  dsn: https://98e1a7982aef43289920a4cdb7961304@sentry.kube.dxos.network/4
  environment: development
