#
# App-specific constants and defaults.
#

app:
  name: 'Arena'
  rootElement: 'root'

devtools: true
snapshots: true

storage:
  persistent: true
  path: dxos/arena-v2

swarm:
  signal: "wss://apollo2.kube.moon.dxos.network/dxos/signal"
  ice:
    - urls: "turn:apollo2.kube.moon.dxos.network:3478"
      username: "dxos"
      credential: "dxos"
wns:
  server: "https://wns1.kube.moon.dxos.network/api"
  chainId: "devnet-2"
ipfs:
  server: "https://apollo2.kube.moon.dxos.network/dxos/ipfs/api"
  gateway: "https://apollo2.kube.moon.dxos.network/dxos/ipfs/gateway/"

debug:
  mode: 'development'
  logging: '*:warn,*:error'

sentry:
  dsn: https://98e1a7982aef43289920a4cdb7961304@sentry.kube.dxos.network/4

invitationExpiration: 240000
