#
# App-specific constants and defaults.
#

app:
  name: 'OXO Game'
  rootElement: 'root'

client:
  devtools: true
  keyStorage:
    root: "dxos/incubator/keys"

  feedStorage:
    root: "dxos/incubator/feeds"

  swarm:
    signal: "ws://localhost:4000"
    ice:
      - urls: "stun:stun.wirelne.ninja:3478"
      - urls: "turn:stun.wireline.ninja:3478"
        username: "wireline"
        credential: "wireline"

debug:
    mode: 'development'
