name: Build and test

on: [pull_request]

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build and test
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn lint
          yarn lint:lockfile
          yarn lint:version
          yarn test
          
      # jest tests with coverage
      - run: yarn test:coverage
      - uses: dxos/jest-reporter-action@0.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "yarn --silent c8 report"

      # The c8 tool leaves tmp folder which is large, we don't want it uploaded to artifacts
      - run: rm -rf coverage/tmp
      # upload coverage report
      # zip file: https://github.com/actions/upload-artifact#zipped-artifact-downloads
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage
